### ISSUE TITLE
error starting asset-transfer-basic chaincode: ccid must be specified

### ISSUE THREAD

**Issue by JohanIskandar** [spydra-tech/fabric-debugger#4]
Hello, 
  
    I wonder when strart debugging give me the following error
```
Starting: /Users/jiskandar/go/bin/dlv dap --check-go-version=false --listen=127.0.0.1:54172 --log-dest=3 from /Users/jiskandar/Workspace/hyperledger-fabric/chaincode
DAP server listening at: 127.0.0.1:54172
Type 'dlv help' for list of commands.
2022/12/16 18:00:01 error starting asset-transfer-basic chaincode: ccid must be specified
```

   I have also read the FAQ and I think I have setup the configuration file correcty for launch.json (configuration using the debug fabric chain code)

```
{
    "configurations": [
    {
        "name": "Debug Chaincode",
        "type": "hlf-go",
        "request": "launch"
    }
    ]
}

```
  Could you please help out how to solve this problem. Thank you.

regards,

Johan

**Comment by ashwath-spdr** [comment]
Hi Johan, thanks for the feedback. Looks like you are trying to debug a Chaincode which is written for the newer Chaincode as a Service model. For that, you need to add an additional parameter in the launch.json file - isCaas: true. The documentation was not clear in this regards. I've rectified that and also made some enhancements for CaaS as well. Please update to the latest version of the plugin, add the above parameter and try again. Pls let me know if that doesn't help.

```
{
    "configurations": [
    {
        "name": "Debug Chaincode",
        "type": "hlf-go",
        "request": "launch",
        "isCaas": true
    }
    ]
}
```

**Comment by JohanIskandar** [comment]
Hi Ashwath,

    Thanks for responding to me. I have added isCass variable but still. Here is the screen capture when debugging

<img width="887" alt="image" src="https://user-images.githubusercontent.com/1010323/208268172-705b171a-e31c-45e7-a0b9-268bc51877ef.png">

     I am not sure how to set CORE_CHAINCODE_ID_NAME. 

regards,

Johan

**Comment by ashwath-spdr** [comment]
Hi @JohanIskandar,
Looks like you are trying a different Chaincode sample this time - https://github.com/hyperledger/fabric-samples/tree/main/asset-transfer-ledger-queries/chaincode-go ?
This one actually is written using the legacy model where the peer will instantiate the chaincode. So, for this, you need to set isCaas=false. You can read about what chaincode as a service model is here: https://hyperledger-fabric.readthedocs.io/en/latest/cc_service.html.

isCaas should be set to true only if the Chaincode is written for the CaaS model. You might have tried the sample https://github.com/hyperledger/fabric-samples/tree/main/asset-transfer-basic/chaincode-external  earlier which is written for the CaaS model.

**Comment by ashwath-spdr** [comment]
@JohanIskandar, just wanted to circle back if you were able to get the debugging working.

**Comment by JohanIskandar** [comment]
Hello,

   Thank you for getting back to me. It is working now and I really
appreciate the awesome plugin that you built.

regards,

Johan

**Comment by ashwath-spdr** [comment]
Thanks for the confirmation! Closing the issue now.
