### ISSUE TITLE
[BUwindwo10, vscode1.78.0, The fabric debugger for node.js cannot be created properly

### ISSUE THREAD

**Issue by 1494119687** [spydra-tech/fabric-debugger#92]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment:**
 - OS: [e.g. Windows 11]
 - Docker version [e.g. 20.10.21]
 - Extension version [e.g. 0.1.1]

**Screenshots**

**Comment by ashwath-spdr** [comment]
Closing this issue as new major release of the debugger should have fixed various stability issues.
